

set CSFunc=%1

if %CSFunc%==CREATE (
	if not exist !CFileName!.txt (
		echo # Configuration file>>!CFileName!.txt
		echo # Generated by ACENet>>!CFileName!.txt
		echo # Any lines with a hashtag are comments>>!CFileName!.txt
		echo.>>!CFileName!.txt
	)
)